server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: common-route
          uri: lb://common
          predicates:
            - Path=/common/**
    nacos:
      discovery:
        server-addr: show.xujiuming.com:8848
  main:
    allow-bean-definition-overriding: true

