server:
  port: 10001
dubbo:
  scan:
    base-packages: com.ming.user.api.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://show.xujiuming.com
spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: show.xujiuming.com:8848
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
