server:
  port: 10002
  servlet:
    context-path: /common
dubbo:
  scan:
    base-packages: com.ming.common.api.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://show.xujiuming.com
spring:
  application:
    name: common
  cloud:
    nacos:
      discovery:
        server-addr: show.xujiuming.com:8848
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
